### ISSUE TITLE
How to download dataset ?

### ISSUE THREAD

**Issue by IamNaQi** [MLNeurosurg/opensrh#1]
I can not find the dataset link for where I can find the dataset for the training or test? Please help

**Comment by chengjia63** [comment]
Please fill out the data request from on our [website](https://opensrh.mlins.org), and upon completion of the data use agreement, you will have access to the links to download the data.

**Comment by arundasan91** [comment]
Hi @chengjia63 , the website is down. Could you please check?

**Comment by chengjia63** [comment]
Hello @arundasan91 , the website seems to be up for me. Please try to check again.

**Comment by arundasan91** [comment]
Thanks for the message. I tried from my home and it worked. Seems like access from my university is blocked.
